
export const CURRENT_LOCATION = 'CURRENT_LOCATION'; // CURRENT_LOCATION
export const DESCRIPTION_LOCATION = 'DESCRIPTION_LOCATION'; //description

export const GET_AVAILABLE = 'GET_AVAILABLE'; // getAvailable